rss_feeds:
    - name: "Republika"
    url: "https://www.republika.co.id/rss"
    - name: "Detik" 
    url: "https://rss.detik.com/index.php/detikterkini"
    - name: "Kompas"
    url: "https://rss.kompas.com/index.xml"

keywords:
    - "politik"
    - "ekonomi" 
    - "daerah"
    - "pendidikan"
    - "kesehatan"
    - "olahraga"
    - "hiburan"
    - "nasional"
