backend:
  name: github
  repo: pandangsaya2023/pulnew
  branch: main

media_folder: "public/media"
public_folder: "/media"

collections:
    - name: "posts"
    label: "Berita"
    folder: "public/posts"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    editor:
      preview: false
    
    fields:
            - {label: "Judul", name: "title", widget: "string", required: true}
            - {label: "Slug", name: "slug", widget: "string", required: true}
            - {label: "Kategori", name: "kategori", widget: "select", options: ["NASIONAL", "POLITIK", "TEKNOLOGI", "OLAHRAGA", "HUKUM", "EKONOMI"], required: true}
            - {label: "Tanggal", name: "date", widget: "datetime", required: true} # <--- INI DIHAPUS FORMAT NYA DULU
            - {label: "Gambar Utama", name: "image", widget: "image", required: false}
            - {label: "Sumber Media", name: "source_name", widget: "string", required: false}
            - {label: "Link Sumber", name: "source_url", widget: "string", required: false}
            - {label: "Isi Berita", name: "body", widget: "markdown", required: true}

    sort: "date"
    sort_direction: "descending"
