site_url: https//pulnew.pages.dev
base_url: /admin
backend:
  name: git-gateway
  repo: pandangsaya2023/pulnew
  branch: main
  base_url: https://odd-moon-077a.pandangsaya2023.workers.dev
  auth_endpoint: auth
  auth_token_endpoint: token
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Berita"
    folder: "public/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "category", widget: "select", options: ["Politik", "Ekonomi", "Hiburan"]}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Isi", name: "body", widget: "markdown"}
