name: Robot Ambil Berita Otomatis

on:
  schedule:
    # Berjalan otomatis setiap 6 jam (00.00, 06.00, 12.00, 18.00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Tombol rahasia agar kita bisa klik "jalan sekarang" secara manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Memeriksa Repositori Kode
      uses: actions/checkout@v3

    - name: Menyiapkan Sistem Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Menjalankan Robot Pengambil Berita
      run: python ambil_berita.py

    - name: Menyimpan Perubahan Kembali ke GitHub
      run: |
        git config --global user.name "Robot Berita Otomatis"
        git config --global user.email "bot@pulnew.com"
        git add public/posts.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update berita otomatis dari media daerah [Skip CI]" && git push)
